<a href="https://colab.research.google.com/github/CodeitVasu/ML/blob/main/Model_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [13]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.975

In [12]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9916666666666667

In [24]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9833333333333333

In [25]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [27]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index)
  print(test_index)

[3 4 5 6 7 8]
[0 1 2]
[0 1 2 6 7 8]
[3 4 5]
[0 1 2 3 4 5]
[6 7 8]


In [28]:
def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)

In [29]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)


In [39]:
scores_l=[]
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
  X_train,X_test,y_train,y_test= digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]

  scores_l.append(get_score(LogisticRegression(),X_train,y_train,X_test,y_test))
  scores_svm.append(get_score(svm,X_train,y_train,X_test,y_test))
  scores_rf.append(get_score(rf,X_train,y_train,X_test,y_test))


ValueError: ignored

In [40]:
from sklearn.model_selection import cross_val_score

In [41]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [44]:
cross_val_score(rf,digits.data,digits.target)

array([0.92777778, 0.9       , 0.95821727, 0.9637883 , 0.92479109])

In [45]:
cross_val_score(lr,digits.data,digits.target)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _che

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])